### ISSUE TITLE
Cannot use in conjunction with ProvidePlugin

### ISSUE THREAD

**Issue by AppSorcery** [rxaviers/globalize-webpack-plugin#18]
ProvidePlugin allows webpack to inject a "require" statement into your code for you.  This is extremely convenient for modules that are used throughout your codebase.

In development mode a single line change in utils.js (line 40):
`var globalizeModule = filepath && isGlobalizeModule(filepath);`
will get it working.

but in production mode you will get:
Error: No formatters or parsers has been provided (#10)

if you go ahead and add a require and formatMessage call once somewhere to bypass the error (suggested workaround for #10), then you get the following bundle error on every file the ProvidePlugin injects the require statement:

TypeError: Cannot read property 'replace' of undefined
        at GlobalizeCompilerHelper.getModuleFilepath (globalize-webpack-plugin/GlobalizeCompilerHelper.js:43:40)
        at GlobalizeCompilerHelper.createCompiledDataModule (globalize-webpack-plugin/GlobalizeCompilerHelper.js:34:23)
        at Parser.<anonymous> (globalize-webpack-plugin/ProductionModePlugin.js:77:58)
        at Parser.applyPluginsBailResult (webpack/node_modules/tapable/lib/Tapable.js:48:50)
        at Parser.<anonymous> (webpack/lib/dependencies/CommonJsRequireDependencyParserPlugin.js:63:22)
        at Parser.applyPluginsBailResult (webpack/node_modules/tapable/lib/Tapable.js:48:50)
        at Parser.walkCallExpression (webpack/lib/Parser.js:651:22)
        at Parser.walkExpression (webpack/lib/Parser.js:513:40)
        at Parser.walkExpressionStatement (webpack/lib/Parser.js:360:7)
        at Parser.walkStatement (webpack/lib/Parser.js:351:32)
        at Parser.<anonymous> (webpack/lib/Parser.js:344:8)
        at Array.forEach (native)
        at Parser.walkStatements (webpack/lib/Parser.js:343:13)
        at Parser.parse (webpack/lib/Parser.js:818:8)
        at Object.ModuleParserHelpers.addParsedVariable (webpack/lib/ModuleParserHelpers.js:10:9)
        at Parser.<anonymous> (webpack/lib/ProvidePlugin.js:36:28)
        at Parser.applyPluginsBailResult (webpack/node_modules/tapable/lib/Tapable.js:48:50)
        at Parser.walkIdentifier (webpack/lib/Parser.js:684:21)
        at Parser.walkExpression (webpack/lib/Parser.js:513:40)
        at Parser.walkMemberExpression (webpack/lib/Parser.js:677:7)
        at Parser.walkExpression (webpack/lib/Parser.js:513:40)
        at Parser.walkCallExpression (webpack/lib/Parser.js:657:9)
        at Parser.walkExpression (webpack/lib/Parser.js:513:40)
        at Parser.<anonymous> (webpack/lib/Parser.js:507:9)
        at Array.forEach (native)
        at Parser.walkExpressions (webpack/lib/Parser.js:505:14)
        at Parser.walkCallExpression (webpack/lib/Parser.js:659:9)
        at Parser.walkExpression (webpack/lib/Parser.js:513:40)
        at Parser.<anonymous> (webpack/lib/Parser.js:507:9)
        at Array.forEach (native)

**Comment by rxaviers** [comment]
Please, could you include a reduced example that demonstrates this issue? You could use [this example](https://github.com/jquery/globalize/tree/master/examples/node-npm) as a baseline for yours.

**Comment by AppSorcery** [comment]
I forked the repo and modified [app-npm-webpack](https://github.com/AppSorcery/globalize/tree/master/examples/app-npm-webpack) to show what i mean, but it's pretty straight forward only 2 changes:

https://github.com/AppSorcery/globalize/blob/3eab85f6dc25c96b99e86f6940892dd92d309fc3/examples/app-npm-webpack/webpack-config.js#L35-L37

https://github.com/AppSorcery/globalize/blob/3eab85f6dc25c96b99e86f6940892dd92d309fc3/examples/app-npm-webpack/app/index.js#L1
(removed the require)

essentially the ProvidePlugin injects 'require("globalize");' into any source file where it finds a Globalize variable (presumably only where Globalize isn't defined)

**Comment by ambrons** [comment]
I am having some issues with globalize + webpack + react-globalize + production builds.  Everything works as expected on the webpack-dev-server.

I've tried a few of the tricks from #10, adding a `Globalize.formateMessage('foo')` to prime the globalize-webpack-plugin / globalize-compiler.  This makes the build work, however I get a error at runtime.  I'll open another ticket with that.  So I started thinking of using `ProvidePlugin` to make `Globalize` global to the application.  I've tried the tweaks in the [above repo](https://github.com/AppSorcery/globalize/tree/master/examples/app-npm-webpack).

So here's my webpack config for the plugin:
```
  new Webpack.ProvidePlugin({
      'Globalize': 'globalize'
  }),
```
I know get the following error at compile time: `npm run build`:
```
Module parse failed: /Users/abrons/devel/zco/esports-ui/node_modules/babel-loader/index.js?{"presets":["es2015","react","stage-0"],"plugins":["syntax-object-rest-spread","transform-decorators-legacy","transform-object-rest-spread","transform-runtime","transform-class-properties"]}!/Users/abrons/devel/zco/esports-ui/src/containers/Root.prod.jsx Cannot read property 'split' of undefined
You may need an appropriate loader to handle this file type.
TypeError: Cannot read property 'split' of undefined
    at isGlobalizeModule (/Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/util.js:8:22)
    at /Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/util.js:40:29
    at Parser.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/globalize-webpack-plugin/ProductionModePlugin.js:68:60)
    at Parser.applyPluginsBailResult (/Users/abrons/devel/zco/esports-ui/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/dependencies/CommonJsRequireDependencyParserPlugin.js:63:22)
    at Parser.applyPluginsBailResult (/Users/abrons/devel/zco/esports-ui/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.walkCallExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:651:22)
    at Parser.walkExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkExpressionStatement (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:360:7)
    at Parser.walkStatement (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:351:32)
    at Parser.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:344:8)
    at Array.forEach (native)
    at Parser.walkStatements (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:343:13)
    at Parser.parse (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:818:8)
    at Object.ModuleParserHelpers.addParsedVariable (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/ModuleParserHelpers.js:10:9)
    at Parser.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/ProvidePlugin.js:36:28)
    at Parser.applyPluginsBailResult (/Users/abrons/devel/zco/esports-ui/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.walkIdentifier (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:684:21)
    at Parser.walkExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkMemberExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:677:7)
    at Parser.walkExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkCallExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:657:9)
    at Parser.walkExpression (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:513:40)
    at Parser.walkExpressionStatement (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:360:7)
    at Parser.walkStatement (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:351:32)
    at Parser.<anonymous> (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:344:8)
    at Array.forEach (native)
    at Parser.walkStatements (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:343:13)
    at Parser.walkBlockStatement (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:356:7)
    at Parser.walkStatement (/Users/abrons/devel/zco/esports-ui/node_modules/webpack/lib/Parser.js:351:32)
 @ ./src/containers/Root.js 4:21-43
```

**Comment by rxaviers** [comment]
@ambrons Please, could you include a reduced example that demonstrates this issue? You could use [this example](https://github.com/jquery/globalize/tree/master/examples/node-npm) as a baseline for yours.

**Comment by rxaviers** [comment]
Please, check how similar from @AppSorcery yours is...

**Comment by AppSorcery** [comment]
you might want to try my fork of [globalize-webpack-plugin](https://github.com/AppSorcery/globalize-webpack-plugin). i don't think the output mechanism of the official repo works well when chaining webpack plugins together.  in my case this only came up in production because i was only doing things like uglify/minify/etc in only in production
